name: 'Country Switcher'
type: module
core_version_requirement: '^8.9 || ^9'
dependencies:
  - 'block_class:block_class'
  - 'datalayer:datalayer'
  - 'drupal:block'
  - 'drupal:content_moderation'
  - 'drupal:field'
  - 'drupal:language'
  - 'drupal:link'
  - 'drupal:menu_ui'
  - 'drupal:node'
  - 'drupal:path'
  - 'drupal:system'
  - 'drupal:taxonomy'
  - 'drupal:user'
  - 'drupal:views'
  - 'field_permissions:field_permissions'
  - 'lightning_workflow:lightning_workflow'
  - 'nppe_module_where_to_buy:nppe_module_where_to_buy'
  - 'rng:rng'
version: 8.x-1.0
description: 'Configuration for country switcher.'
