<?php

/**
 * @file
 * Contains nhsc_content_manager.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Render\PlainTextOutput;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\nhsc_user_profile\Controller\PageController;
use Drupal\user\Entity\User;
use Drupal\Core\Render\Markup;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\InvokeCommand;

/**
 * Implements hook_help().
 */
function nhsc_content_manager_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the nhsc_content_manager module.
        case 'help.page.nhsc_content_manager':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Nestle Heath Sciences Content Manager') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implementation of hook_theme().
 */
function nhsc_content_manager_theme($existing, $type, $theme, $path)
{
    return [
        'custom_add_content' => [
            'render element' => 'form',
        ],
        'add_article_button_block' => [
            'variables' => ['description' => NULL, 'link_text' => NULL, 'link_url' => NULL],
            'template' => 'block--add-article-button',
        ]

    ];
}

/**
 * Implements hook_form_alter().
 */
function nhsc_content_manager_form_alter(&$form, FormStateInterface &$form_state, $form_id)
{
    switch ($form_id) {
        case "nhsc_cm_add_aritcle_form":
            $form['#theme'] = 'custom_add_content';
            break;
    }
}