<?php

/**
 * @file
 * Contains nhsc_custom_schema.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\nhsc_self_assessment_survey\Controller\SelfAssessmentController;
use Drupal\block\Entity\Block;
use Drupal\node\NodeInterface;
/**
 * Implements hook_help().
 */
function nhsc_self_assessment_survey_help($route_name, RouteMatchInterface $route_match) {
    $output = '';
    switch ($route_name) {
        case 'help.page.nhsc_self_assessment_survey':
            $output = '';
            $output .= '<h3>' . t('Self Assessment Survey') . '</h3>';
            $output .= '<h4>' . t('Usage: ') . '</h4>';
            $output .= '<ul>';
            $output .= '</ul>';

    }

    return $output;
}

/**
 * Implements hook_theme().
 */
function nhsc_self_assessment_survey_theme()
{
    return [
        'nhsc_self_assessment_survey' => [
            'variables' => [
                'survey_data' => NULL,
                'main_bunner' => NULL,
                'result_data' => NULL,
            ],
            'template' => 'nhsc-self-assessment-survey',
        ]
    ];
}

/**
 * Implements hook_page_attachments().
 */
function nhsc_self_assessment_survey_page_attachments(array &$page) {

}

/**
 * Implements hook_preprocess_block().
 */
function nhsc_self_assessment_survey_preprocess_block (&$variables) {

    if ($variables['elements']['#plugin_id'] == 'self_assessment_survey_block') {

        $variables['#attached']['library'][] = 'nhsc_self_assessment_survey/self-assessment-survey-form';
        $controller     = new SelfAssessmentController();
        $config         = $controller->getConfigs();

        $data = [
            'result_a_score' => $config->get('result_a_score'),
            'result_b_score' => $config->get('result_b_score'),
            'result_c_score' => $config->get('result_c_score'),
        ];

        $variables['#attached']['drupalSettings']['nhsc_self_assessment_survey'] = $data;
    }

}

/**
 * Implements hook_preprocess_HOOK().
 * @param
 */
function nhsc_self_assessment_survey_preprocess_html(&$variables) {

	$node = \Drupal::routeMatch()->getParameter('node');
	if ($node instanceof NodeInterface) {
		// Test if node is self assessment
		if ($node->hasField('field_survey_type')) {
			if ($survey = $node->get('field_survey_type')->getValue()) {
				if ($survey[0]['plugin_id'] == 'self_assessment_survey_block' ){
					$variables['attributes']['class'][] = 'page-self-assessment';
				}
			}
		}
	}


}