# The 'type' should be "label" for short meta tags and "text" for ones which
# could get longer, especially ones which use a textarea field instead of a
# textfield.

metatag.metatag_tag.schema_multiple_products_type:
  type: text
  label: '@type'
metatag.metatag_tag.schema_multiple_products_item_list:
  type: text
  label: 'Item List Element'
