<?php

/**
 * @file
 * Contains nhsc_custom_schema.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\nhsc_symptom_checker\Controller\SymptomCheckerController;

/**
 * Implements hook_help().
 */
function nhsc_symptom_checker_help($route_name, RouteMatchInterface $route_match) {
    $output = '';
    switch ($route_name) {
        case 'help.page.nhsc_symptom_checker':
            $output = '';
            $output .= '<h3>' . t('Symptom Checker') . '</h3>';
            $output .= '<h4>' . t('Usage: ') . '</h4>';
            $output .= '<ul>';
            $output .= '</ul>';

    }

    return $output;
}

/**
 * Implements hook_theme().
 */
function nhsc_symptom_checker_theme()
{
    return [
        'nhsc_symptom_checker' => [
            'variables' => [
                'survey_data' => NULL,
                'main_bunner' => NULL,
                'result_data' => NULL,
                'first_question' => NULL,
            ],
            'template' => 'nhsc-symptom-checker',
        ]
    ];
}

/**
 * Implements hook_page_attachments().
 */
function nhsc_symptom_checker_page_attachments(array &$page)
{
    //

}

/**
 * Implements hook_preprocess_block().
 */
function nhsc_symptom_checker_preprocess_block (&$variables)
{
    if ($variables['elements']['#plugin_id'] == 'nhsc_symptom_checker') {
        $variables['#attached']['library'][] = 'nhsc_symptom_checker/symptom-checker-form';
    }
}