excluded:
  - block.block.corporate_vitaflo_views_block__nhsc_banner_buttons_block_1
  - block.block.corporate_vitaflo_views_block__nhsc_bottom_buttons_block_1
  - block.block.corporate_vitaflo_views_block__nhsc_faq_block_block_1
  - block.block.corporate_vitaflo_views_block__nhsc_master_icons_block_block_1
  - block.block.corporate_vitaflo_views_block__nhsc_master_people_slider_block_1
  - block.block.corporate_vitaflo_views_block__nhsc_new_master_image_slider_top_block_1
  - block.block.corporate_vitaflo_views_block__people_slider_block_1
  - block.block.nestlehcp_views_block__nhsc_banner_buttons_block_1
  - block.block.nestlehcp_views_block__nhsc_bottom_buttons_block_1
  - block.block.nestlehcp_views_block__nhsc_faq_block_block_1
  - block.block.nestlehcp_views_block__nhsc_master_icons_block_block_1
  - block.block.nestlehcp_views_block__nhsc_master_people_slider_block_1
  - block.block.nestlehcp_views_block__nhsc_new_master_image_slider_top_block_1
  - block.block.nestlehcp_views_block__people_slider_block_1
  - block.block.nhsc_mychildcerebralpalsy_views_block__nhsc_banner_buttons_block_1
  - block.block.nhsc_mychildcerebralpalsy_views_block__nhsc_bottom_buttons_block_1
  - block.block.nhsc_mychildcerebralpalsy_views_block__nhsc_faq_block_block_1
  - block.block.nhsc_mychildcerebralpalsy_views_block__nhsc_master_icons_block_block_1
  - block.block.nhsc_mychildcerebralpalsy_views_block__nhsc_master_people_slider_block_1
  - block.block.nhsc_mychildcerebralpalsy_views_block__nhsc_new_master_image_slider_top_block_1
  - block.block.nhsc_mychildcerebralpalsy_views_block__pc_protein_calculator_slider_tab_block_1
  - block.block.nhsc_mychildcerebralpalsy_views_block__people_slider_block_1
  - block.block.views_block__nhsc_banner_buttons_block_1
  - block.block.views_block__nhsc_bottom_buttons_block_1
  - block.block.views_block__nhsc_faq_block_block_1
  - block.block.views_block__nhsc_master_icons_block_block_1
  - block.block.views_block__nhsc_master_people_slider_block_1
  - block.block.views_block__nhsc_new_master_image_slider_top_block_1
  - block.block.views_block__pc_product_banner_block_1_2
  - block.block.views_block__pc_protein_calculator_slider_tab_block_1
  - block.block.views_block__people_slider_block_1
  - block.block.bartik_main_menu
  - block.block.bootstrap_main_menu
  - block.block.corporate_vitaflo_mainnavigation
  - block.block.mainnavigation
  - block.block.nestlehcp_mainnavigation
  - block.block.nhsc_mychildcerebralpalsy_mainnavigation
  - metatag.metatag_defaults.taxonomy_term__cerebral_palsy_tool
  - user.role.content_manager_whitelabel_
  - views.view.custom_article_list_
required: true
