<?php

/**
 * @file
 * Contains hcp_site_switcher.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;
use Drupal\Core\Render\Markup;
use Drupal\hcp_site_switcher\Controller\SiteToggleController;
/**
 * Implements hook_help().
 */
function hcp_site_switcher_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the hcp_site_switcher module.
        case 'help.page.hcp_site_switcher':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Toggle content for HCP professionals') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_page_attachments().
 */
function hcp_site_switcher_page_attachments(array &$page) {

    $page['#attached']['library'][] = 'hcp_site_switcher/hcp-site-switcher-js';

    $site_toggle = new SiteToggleController();
    $node_info = $site_toggle->getNodeUrlInfo();

    \Drupal::service('renderer')->addCacheableDependency($page, $node_info);

    $page['#attached']['drupalSettings']['hcp_site_switcher'] = $node_info;

}

/**
 * Implements hook_preprocess_menu().
 */
function hcp_site_switcher_preprocess_menu(&$variables, $hook)
{
  if ($hook == 'menu__main') { // We're doing that for main menu.
    // Get the current path.
    $current_path = \Drupal::request()->getRequestUri();
    $items = $variables['items'];
    foreach ($items as $key => $item) {
      // If path is current_path, set active to li.
      if ($item['url']->toString() == $current_path) {
        // Add active link.
        $variables['items'][$key]['attributes']['class'] = 'active';
      }
    }
  }
}
