<?php

/**
 * @file
 * Contains nhsc_custom_schema.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\nhsc_comiss_score_survey\Controller\ComissScoreController;

/**
 * Implements hook_help().
 */
function nhsc_comiss_score_survey_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.nhsc_comiss_score_survey':
            $output = '';
            $output .= '<h3>' . t('Comiss Score Survey') . '</h3>';
            $output .= '<h4>' . t('Usage: ') . '</h4>';
            $output .= '<ul>';
            $output .= '</ul>';
            return $output;
    }
}

/**
 * Implements hook_page_attachments().
 */
function nhsc_comiss_score_survey_page_attachments(array &$page) {
//    $variables['#attached']['library'][] = 'nhsc_comiss_score_survey/comiss-score-pdf';
}


/**
 * Implements hook_theme().
 */
function nhsc_comiss_score_survey_theme()
{
    return [
        'nhsc_comiss_score_survey' => [
            'variables' => [
                'intro_copy' => NULL,
                'form' => NULL,
                'survey_title' => NULL,
                'purpose_title' => NULL,
                'purpose_copy' => NULL,
                'instructions_title' => NULL,
                'instructions_copy' => NULL,
                'reading_results_title' => NULL,
                'reading_results_copy' => NULL,
                'form_print_footer' => NULL,
                'footer_logo' => NULL,
                'copy_right_text' => NULL,
                'responses' => NULL,
                'questions' => NULL,
            ],
            'template' => 'nhsc-comiss-score-survey',

        ],
        'nhsc_comiss_score_survey_pdf' => [
            'variables' => [
                'survey_title' => NULL,
                'purpose_title' => NULL,
                'purpose_copy' => NULL,
                'instructions_title' => NULL,
                'instructions_copy' => NULL,
                'reading_results_title' => NULL,
                'reading_results_copy' => NULL,
                'form_print_footer' => NULL,
                'footer_logo' => NULL,
                'copy_right_text' => NULL,
                'questions' => NULL,
             ]
        ],
        'nhsc_comiss_score_survey_print_results' => [
            'variables' => [
                'test' => NULL,
            ]
        ],
    ];
}

/**
 * Implements hook_preprocess_block().
 */
function nhsc_comiss_score_survey_preprocess_block (&$variables) {


    if ($variables['elements']['#plugin_id'] == 'comiss_score_block') {
        $variables['#attached']['library'][] = 'nhsc_comiss_score_survey/comiss-score-form';

        $controller     = new ComissScoreController();
        $config         = $controller->getConfigs();

        $comiss_score_above_cutoff_copy = (empty($variables['elements']['#configuration']['block_above_cutoff'])) ? $config->get('comiss_score_above_cutoff') : $variables['elements']['#configuration']['block_above_cutoff'];
        $above_first_cta_link           = (empty($variables['elements']['#configuration']['block_above_first_cta_link'])) ? $config->get('above_first_cta_link') : $variables['elements']['#configuration']['block_above_first_cta_link'];
        $above_first_cta_text           = (empty($variables['elements']['#configuration']['block_above_first_cta_text'])) ? $config->get('above_first_cta_text') : $variables['elements']['#configuration']['block_above_first_cta_text'];
        $above_second_cta_link          = (empty($variables['elements']['#configuration']['block_above_second_cta_link'])) ? $config->get('above_second_cta_link') : $variables['elements']['#configuration']['block_above_second_cta_link'];
        $above_second_cta_text          = (empty($variables['elements']['#configuration']['block_above_second_cta_text'])) ? $config->get('above_second_cta_text') : $variables['elements']['#configuration']['block_above_second_cta_text'];
        $comiss_score_below_cutoff_copy = (empty($variables['elements']['#configuration']['block_comiss_score_below_cutoff'])) ? $config->get('comiss_score_below_cutoff') : $variables['elements']['#configuration']['block_comiss_score_below_cutoff'];
        $below_first_cta_link           = (empty($variables['elements']['#configuration']['block_below_first_cta_link'])) ? $config->get('below_first_cta_link') : $variables['elements']['#configuration']['block_below_first_cta_link'];
        $below_first_cta_text           = (empty($variables['elements']['#configuration']['block_below_first_cta_text'])) ? $config->get('below_first_cta_text') : $variables['elements']['#configuration']['block_below_first_cta_text'];
        $below_second_cta_link          = (empty($variables['elements']['#configuration']['block_below_second_cta_link'])) ? $config->get('below_second_cta_link') : $variables['elements']['#configuration']['block_below_second_cta_link'];
        $below_second_cta_text          = (empty($variables['elements']['#configuration']['block_below_second_cta_text'])) ? $config->get('below_second_cta_text') : $variables['elements']['#configuration']['block_below_second_cta_text'];
        $comiss_score_cutoff_value      = (empty($variables['elements']['#configuration']['block_comiss_score_cutoff_value'])) ? $config->get('comiss_score_cutoff_value') : $variables['elements']['#configuration']['block_comiss_score_cutoff_value'];



        $data = [
            'above_cutoff_copy' => $comiss_score_above_cutoff_copy,
            'above_first_cta_link' => $above_first_cta_link,
            'above_first_cta_text' => $above_first_cta_text,
            'above_second_cta_link' => $above_second_cta_link,
            'above_second_cta_text' => $above_second_cta_text,

            'below_cutoff_copy' => $comiss_score_below_cutoff_copy,
            'below_first_cta_link' => $below_first_cta_link,
            'below_first_cta_text' => $below_first_cta_text,
            'below_second_cta_link' => $below_second_cta_link,
            'below_second_cta_text' => $below_second_cta_text,

            'comiss_score_cutoff_value' => $comiss_score_cutoff_value,
        ];

        $variables['#attached']['drupalSettings']['nhsc_comiss_score_survey'] = $data;
    }
}
