<?php

use Drupal\views\Views;
use Drupal\Core\Url;
use Drupal\block\Entity\Block;
use Drupal\Core\Entity\EntityInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**

/**
 * Implements hook_theme_registry_alter
 */

function nppe_module_where_to_buy_theme_registry_alter(&$theme_registry) {

	$current_path = \Drupal::service('path.current')->getPath();

	$path = explode('/', $current_path);

	$path = $path['1'];

	$view = \Drupal::service('entity_type.manager')->getStorage('view')->load('nppe_where_to_buy');

    $view_path = $view->getDisplay('page_1')['display_options']['path'];

	if ($path == $view_path) {

		$theme_registry['views_view']['path'] = drupal_get_path('module', 'nppe_module_where_to_buy') . '/templates';

	}

}

function nppe_module_where_to_buy_page_attachments(array &$page) {

	$page['#attached']['library'][] = 'nppe_module_where_to_buy/nppe_module_where_to_buy_js';

}


function nppe_module_where_to_buy_preprocess_views_view(&$variables) {

    $block = Block::load('searchblock');

    if (!empty($block)) {

        $block_content = \Drupal::entityTypeManager()
            ->getViewBuilder('block')
            ->view($block);
        $variables['search_block'] = \Drupal::service('renderer')->render($block_content);

    }

}

/**
 * Implements hook_theme().
 */
function nppe_module_where_to_buy_theme()
{
    return [
        'office_search_form' => [
            'variables' => [
                'form' => NULL,
            ],
            'template' => 'office-search-form',
        ],
    ];
}

/**
 * Implements hook_preprocess_block().
 */
function nppe_module_where_to_buy_preprocess_block (&$variables) {

}
