<?php

/**
 * @file
 * Contains schema_question.module.
 */

/**
 * Implements hook_token_info().
 */
function schema_question_token_info() {
    $type = [
        'name' => t('FAQ Tokens'),
        'description' => t('Tokens for FAQs.'),
    ];

    $node['titles'] = [
        'name' => t("Question Title"),
        'description' => t('The Question title'),
    ];

    $node['questions'] = [
        'name' => t("Questions"),
        'description' => t('List of questions'),
    ];

    $node['answers'] = [
        'name' => t("Answers"),
        'description' => t('List of answers'),
    ];

    return [
        'types' => ['FAQ_token' => $type],
        'tokens' => ['FAQ_token' => $node],
    ];
}

/**
 * Implements hook_tokens().
 */
function schema_question_tokens($type, $tokens, array $data, array $options, \Drupal\Core\Render\BubbleableMetadata $bubbleable_metadata) {
    $replacements = [];

    $node = \Drupal::routeMatch()->getParameter('node');

    $main_titles = [];
    $faq_questions = [];
    $faq_answers = [];

    if ($node instanceof \Drupal\node\NodeInterface ) {

        if ($node->hasField('field_nhsc_faq')) {

            $field = $node->get('field_nhsc_faq');
            $paragraphs = $field->referencedEntities();

            foreach ($paragraphs as $paragraph) {


                if($paragraph->getType() === 'nhsc_multiple_faq'){
                    //field_nhsc_multiple_faq_item
                    $main_title = $paragraph->get('field_title')->value;

                    $main_titles[] = $main_title;

                    // slider items
                    $sliders = $paragraph->get('field_nhsc_multiple_faq_item')->referencedEntities();
                    foreach ($sliders as $slider) {
                        $faq_title = $slider->get('field_title')->value;
                        $faq_body = $slider->get('field_body')->value;

                        $faq_questions[] = $faq_title;
                        $faq_answers[]      = $faq_body;
                    }

                }


            }

        }


    }


    if ($type == 'FAQ_token' && !empty($data['node'])) {
        foreach ($tokens as $name => $original) {
            switch ($name) {
                case 'titles':
                    $replacements[$original] = implode(',', $main_titles);
                    break;
                case 'questions':
                    $replacements[$original] = implode(',', $faq_questions);
                    break;
                case 'answers':
                    $replacements[$original] = implode(',', $faq_answers);
                    break;
            }
        }

    }
    return $replacements;
}